name: jetson-nano-x11
version: '0.1'
summary: X11 for Jetson Nano
description: X11 desktop for Jetson Nano
confinement: devmode
grade: devel
base: core18
architectures: [ arm64 ]

apps:
    xrandr:
        command: bin/xrandr.sh
        aliases: [ jetson-nano-x11_xrandr ]
    xeyes:
        command: bin/xwrapper.sh xeyes
        aliases: [ jetson-nano-x11_xeyes ]
    xorg:
        command: bin/xorg.sh
        aliases: [ jetson-nano-x11_xorg ]
    xserver:
        command: bin/start-x.sh

layout:
  /etc:
    bind: $SNAP/etc
  /usr/lib/xorg:
    bind: $SNAP/usr/lib/xorg
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/themes:
    bind: $SNAP/usr/share/themes
  /usr/bin:
    bind: $SNAP/usr/bin

parts:
    # Grabs X11 binaries
    x11:
        plugin: nil
        stage-packages:
            - libwayland-client0
            - libwayland-server0
            - x11-apps
            - xorg
            - xserver-xorg-video-fbdev
            - openbox
            - python
            - python-xdg
        stage:
            - -usr/bin/Xorg
            - -etc/X11/Xsession.d/70im-config_launch
            - -etc/X11/Xsession.d/75dbus_dbus-launch
            - -etc/X11/xinit/xinitrc
            - -usr/lib/gcc
            - -usr/lib/man-db
            - -usr/lib/tmpfiles.d
            - -usr/lib/mime
            - -usr/lib/groff
            - -usr/include/xorg
            - -usr/share/doc
            - -usr/share/doc-base
            - -usr/share/calendar
            - -usr/share/applications
            - -usr/share/man
            - -usr/share/man-db
            - -usr/share/menu
            - -var
            - -etc/cron.daily
            - -etc/cron.weekly
            - -etc/calendar

    # Library that adds $SNAP prefix to paths in calls to glibc
    snappypreload:
      plugin: cmake
      source: src
      build-packages:
        - build-essential

    nvidia-l4t-3d-core:
      plugin: dump
      source: nvidia/nvidia-l4t-3d-core_32.2.0-20190716172031_arm64.deb
      override-build: |
        rm etc/vulkan/icd.d/nvidia_icd.json
        ln -s ../../../usr/lib/aarch64-linux-gnu/tegra/nvidia_icd.json \
            etc/vulkan/icd.d/nvidia_icd.json
        snapcraftctl build
    nvidia-l4t-core:
      plugin: dump
      source: nvidia/nvidia-l4t-core_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-ccp-t210ref:
      plugin: dump
      source: nvidia/nvidia-l4t-ccp-t210ref_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-init:
      plugin: dump
      source: nvidia/nvidia-l4t-init_32.2.0-20190716172031_arm64.deb
      override-build: |
        rm etc/systemd/system/nv-l4t-usb-device-mode-runtime.service
        rm etc/systemd/system/nv-l4t-usb-device-mode.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode-runtime.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service
        ln -s ../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime.service \
            etc/systemd/system/nv-l4t-usb-device-mode-runtime.service
        ln -s ../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode.service \
            etc/systemd/system/nv-l4t-usb-device-mode.service
        ln -s ../../../../opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service
        ln -s ../../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode-runtime.service
        ln -s ../../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service
        snapcraftctl build
    nvidia-l4t-firmware:
      plugin: dump
      source: nvidia/nvidia-l4t-firmware_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-x11:
      plugin: dump
      source: nvidia/nvidia-l4t-x11_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-wayland:
      plugin: dump
      source: nvidia/nvidia-l4t-wayland_32.2.0-20190716172031_arm64.deb

    overlay:
      plugin: dump
      source: overlay
