name: jetson-nano-x11
version: '0.1'
summary: X11 for Jetson Nano
description: X11 desktop for Jetson Nano
confinement: strict
grade: stable
base: core18
architectures: [ arm64 ]

slots:
  x11-server: x11

plugs:
  x11-client: x11

apps:
    xrandr:
        command: bin/xwrapper.sh xrandr
        plugs: [ x11-client, network ]
    xeyes:
        command: bin/xwrapper.sh xeyes
        plugs: [ x11-client, network ]
    particles:
        command: bin/xwrapper.sh particles
        plugs: [ x11-client, network, opengl ]
    marchingCubes:
        command: bin/xwrapper.sh marchingCubes
        plugs: [ x11-client, network, opengl ]
    xorg:
        command: bin/xorg.sh
        slots: [ x11-server ]
        plugs: [ network-bind, opengl, framebuffer ]
    xserver:
        command: bin/start-x.sh
        slots: [ x11-server ]
        plugs: [ network-bind, opengl, framebuffer ]

layout:
  /etc:
    bind: $SNAP/etc
  /usr/lib/aarch64-linux-gnu/dri:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/dri
  /usr/lib/xorg:
    bind: $SNAP/usr/lib/xorg
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/themes:
    bind: $SNAP/usr/share/themes
  /usr/bin:
    bind: $SNAP/usr/bin
  /var/log:
    bind: $SNAP_DATA/var/log

parts:
    # Grabs X11 binaries
    x11:
        plugin: nil
        stage-packages:
            - coreutils
            - freeglut3
            - libwayland-client0
            - libwayland-server0
            - x11-apps
            - xorg
            - xserver-xorg-video-fbdev
            - openbox
            - python
            - python-xdg
            - util-linux
            - xterm
        stage:
            - -usr/bin/Xorg
            - -etc/X11/Xsession.d/70im-config_launch
            - -etc/X11/Xsession.d/75dbus_dbus-launch
            - -etc/X11/xinit/xinitrc
            - -usr/lib/gcc
            - -usr/lib/man-db
            - -usr/lib/tmpfiles.d
            - -usr/lib/mime
            - -usr/lib/groff
            - -usr/include/xorg
            - -usr/share/doc
            - -usr/share/doc-base
            - -usr/share/calendar
            - -usr/share/applications
            - -usr/share/man
            - -usr/share/man-db
            - -usr/share/menu
            - -var
            - -etc/cron.daily
            - -etc/cron.weekly
            - -etc/calendar
        override-stage: |
            snapcraftctl stage
            sed -i 's#/usr/lib/#$SNAP/usr/lib/#g' usr/bin/openbox-session usr/lib/*/openbox-autostart

    nvidia-l4t-3d-core:
      plugin: dump
      source: nvidia/nvidia-l4t-3d-core_32.2.0-20190716172031_arm64.deb
      override-build: |
        rm etc/vulkan/icd.d/nvidia_icd.json
        ln -s ../../../usr/lib/aarch64-linux-gnu/tegra/nvidia_icd.json \
            etc/vulkan/icd.d/nvidia_icd.json
        snapcraftctl build
    nvidia-l4t-core:
      plugin: dump
      source: nvidia/nvidia-l4t-core_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-ccp-t210ref:
      plugin: dump
      source: nvidia/nvidia-l4t-ccp-t210ref_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-init:
      plugin: dump
      source: nvidia/nvidia-l4t-init_32.2.0-20190716172031_arm64.deb
      override-build: |
        rm etc/systemd/system/nv-l4t-usb-device-mode-runtime.service
        rm etc/systemd/system/nv-l4t-usb-device-mode.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode-runtime.service
        rm etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service
        ln -s ../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime.service \
            etc/systemd/system/nv-l4t-usb-device-mode-runtime.service
        ln -s ../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode.service \
            etc/systemd/system/nv-l4t-usb-device-mode.service
        ln -s ../../../../opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service
        ln -s ../../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode-runtime.service
        ln -s ../../../../opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode.service \
            etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service
        snapcraftctl build
    nvidia-l4t-firmware:
      plugin: dump
      source: nvidia/nvidia-l4t-firmware_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-x11:
      plugin: dump
      source: nvidia/nvidia-l4t-x11_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-wayland:
      plugin: dump
      source: nvidia/nvidia-l4t-wayland_32.2.0-20190716172031_arm64.deb
    nvidia-l4t-cuda:
      plugin: dump
      source: nvidia/nvidia-l4t-cuda_32.2.0-20190716172031_arm64.deb
      override-build: |
        ln -s libcuda.so.1.1 usr/lib/aarch64-linux-gnu/tegra/libcuda.so.1
        snapcraftctl build

    overlay:
      plugin: dump
      source: overlay

    cuda-samples:
      plugin: dump
      source: cuda-samples
